### ISSUE TITLE
Store build artifacts for pull requests and releases

### ISSUE THREAD

**Issue by ggutierrez-sunbright** [CBDD/rDock#43]
Having those artifacts readily available for download serves two purposes:
* allowing users to simply download the pre-compiled binaries if they are using any of the supported distributions
* allowing CI pipeline to check for performance regressions comparing execution times for the currently released binary and the new candidate.

sub-tasks:
- [x] create the bundle files after testing (#44)
- [x] store them as artifacts (#44)
  - [ ] fix naming for artifacts in CI (?)
- [x] create a release whenever there's a merge to main (#46)
- [ ] push the bundled files as release assets (#48)
